services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    container_name: "api"
    depends_on:
      - mongodb
    env_file:
      - ./.env
    ports:
      - "4000:4000"
    restart: unless-stopped
    volumes:
      - .:/app

  mongodb:
    image: mongo
    container_name: "mongodb"
    ports:
      - "27017-27019:27017-27019"
    logging:
      driver: 'none'
    restart: unless-stopped
    volumes:
      - data-mongodb:/data/db
    command: --quiet --logpath /dev/null 

volumes:
  data-mongodb:
